export interface SurahMeta {
  number: number;
  name: string;
  transliteration: string;
  translation: string;
  ayahCount: number;
  revelationType: "Mekke" | "Medine";
}

export const SURAHS: SurahMeta[] = [
  { number: 1, name: "الفاتحة", transliteration: "El-Fatiha", translation: "Hapja", ayahCount: 7, revelationType: "Mekke" },
  { number: 2, name: "البقرة", transliteration: "El-Bekare", translation: "Lopa", ayahCount: 286, revelationType: "Medine" },
  { number: 3, name: "آل عمران", transliteration: "Ali Imran", translation: "Familja e Imranit", ayahCount: 200, revelationType: "Medine" },
  { number: 4, name: "النساء", transliteration: "En-Nisa", translation: "Grate", ayahCount: 176, revelationType: "Medine" },
  { number: 5, name: "المائدة", transliteration: "El-Maide", translation: "Sofra", ayahCount: 120, revelationType: "Medine" },
  { number: 6, name: "الأنعام", transliteration: "El-En'am", translation: "Bagëtitë", ayahCount: 165, revelationType: "Mekke" },
  { number: 7, name: "الأعراف", transliteration: "El-A'raf", translation: "Vendet e Larta", ayahCount: 206, revelationType: "Mekke" },
  { number: 8, name: "الأنفال", transliteration: "El-Enfal", translation: "Preja e Luftës", ayahCount: 75, revelationType: "Medine" },
  { number: 9, name: "التوبة", transliteration: "Et-Teube", translation: "Pendimi", ayahCount: 129, revelationType: "Medine" },
  { number: 10, name: "يونس", transliteration: "Junus", translation: "Junusi", ayahCount: 109, revelationType: "Mekke" },
  { number: 11, name: "هود", transliteration: "Hud", translation: "Hudi", ayahCount: 123, revelationType: "Mekke" },
  { number: 12, name: "يوسف", transliteration: "Jusuf", translation: "Jusufi", ayahCount: 111, revelationType: "Mekke" },
  { number: 13, name: "الرعد", transliteration: "Er-Ra'd", translation: "Bubullima", ayahCount: 43, revelationType: "Medine" },
  { number: 14, name: "إبراهيم", transliteration: "Ibrahim", translation: "Ibrahimi", ayahCount: 52, revelationType: "Mekke" },
  { number: 15, name: "الحجر", transliteration: "El-Hixhr", translation: "Shkëmbi", ayahCount: 99, revelationType: "Mekke" },
  { number: 16, name: "النحل", transliteration: "En-Nahl", translation: "Bleta", ayahCount: 128, revelationType: "Mekke" },
  { number: 17, name: "الإسراء", transliteration: "El-Isra", translation: "Udhëtimi Natën", ayahCount: 111, revelationType: "Mekke" },
  { number: 18, name: "الكهف", transliteration: "El-Kehf", translation: "Shpella", ayahCount: 110, revelationType: "Mekke" },
  { number: 19, name: "مريم", transliteration: "Merjem", translation: "Merjemja", ayahCount: 98, revelationType: "Mekke" },
  { number: 20, name: "طه", transliteration: "Ta-Ha", translation: "Ta-Ha", ayahCount: 135, revelationType: "Mekke" },
  { number: 21, name: "الأنبياء", transliteration: "El-Enbija", translation: "Profetët", ayahCount: 112, revelationType: "Mekke" },
  { number: 22, name: "الحج", transliteration: "El-Haxhxh", translation: "Haxhi", ayahCount: 78, revelationType: "Medine" },
  { number: 23, name: "المؤمنون", transliteration: "El-Mu'minun", translation: "Besimtarët", ayahCount: 118, revelationType: "Mekke" },
  { number: 24, name: "النور", transliteration: "En-Nur", translation: "Drita", ayahCount: 64, revelationType: "Medine" },
  { number: 25, name: "الفرقان", transliteration: "El-Furkan", translation: "Dallimi", ayahCount: 77, revelationType: "Mekke" },
  { number: 26, name: "الشعراء", transliteration: "Esh-Shu'ara", translation: "Poetët", ayahCount: 227, revelationType: "Mekke" },
  { number: 27, name: "النمل", transliteration: "En-Neml", translation: "Milingona", ayahCount: 93, revelationType: "Mekke" },
  { number: 28, name: "القصص", transliteration: "El-Kasas", translation: "Tregimet", ayahCount: 88, revelationType: "Mekke" },
  { number: 29, name: "العنكبوت", transliteration: "El-Ankebut", translation: "Merimanga", ayahCount: 69, revelationType: "Mekke" },
  { number: 30, name: "الروم", transliteration: "Er-Rum", translation: "Romakët", ayahCount: 60, revelationType: "Mekke" },
  { number: 31, name: "لقمان", transliteration: "Llukman", translation: "Llukmani", ayahCount: 34, revelationType: "Mekke" },
  { number: 32, name: "السجدة", transliteration: "Es-Sexhde", translation: "Sexhdeja", ayahCount: 30, revelationType: "Mekke" },
  { number: 33, name: "الأحزاب", transliteration: "El-Ahzab", translation: "Aleatët", ayahCount: 73, revelationType: "Medine" },
  { number: 34, name: "سبأ", transliteration: "Sebe", translation: "Sabaja", ayahCount: 54, revelationType: "Mekke" },
  { number: 35, name: "فاطر", transliteration: "Fatir", translation: "Krijuesi", ayahCount: 45, revelationType: "Mekke" },
  { number: 36, name: "يس", transliteration: "Ja-Sin", translation: "Ja-Sin", ayahCount: 83, revelationType: "Mekke" },
  { number: 37, name: "الصافات", transliteration: "Es-Saffat", translation: "Të Radhiturit", ayahCount: 182, revelationType: "Mekke" },
  { number: 38, name: "ص", transliteration: "Sad", translation: "Sad", ayahCount: 88, revelationType: "Mekke" },
  { number: 39, name: "الزمر", transliteration: "Ez-Zumer", translation: "Grupet", ayahCount: 75, revelationType: "Mekke" },
  { number: 40, name: "غافر", transliteration: "Gafir", translation: "Falësi", ayahCount: 85, revelationType: "Mekke" },
  { number: 41, name: "فصلت", transliteration: "Fussilet", translation: "Të Shpjeguarat", ayahCount: 54, revelationType: "Mekke" },
  { number: 42, name: "الشورى", transliteration: "Esh-Shura", translation: "Konsultimi", ayahCount: 53, revelationType: "Mekke" },
  { number: 43, name: "الزخرف", transliteration: "Ez-Zuhruf", translation: "Zbukurimet", ayahCount: 89, revelationType: "Mekke" },
  { number: 44, name: "الدخان", transliteration: "Ed-Duhan", translation: "Tymi", ayahCount: 59, revelationType: "Mekke" },
  { number: 45, name: "الجاثية", transliteration: "El-Xhathije", translation: "Gjunjëzimi", ayahCount: 37, revelationType: "Mekke" },
  { number: 46, name: "الأحقاف", transliteration: "El-Ahkaf", translation: "Dunat e Rërës", ayahCount: 35, revelationType: "Mekke" },
  { number: 47, name: "محمد", transliteration: "Muhammed", translation: "Muhammedi", ayahCount: 38, revelationType: "Medine" },
  { number: 48, name: "الفتح", transliteration: "El-Fet'h", translation: "Çlirimi", ayahCount: 29, revelationType: "Medine" },
  { number: 49, name: "الحجرات", transliteration: "El-Huxhurat", translation: "Dhomat", ayahCount: 18, revelationType: "Medine" },
  { number: 50, name: "ق", transliteration: "Kaf", translation: "Kaf", ayahCount: 45, revelationType: "Mekke" },
  { number: 51, name: "الذاريات", transliteration: "Edh-Dharijat", translation: "Erërat Shpërndarëse", ayahCount: 60, revelationType: "Mekke" },
  { number: 52, name: "الطور", transliteration: "Et-Tur", translation: "Mali", ayahCount: 49, revelationType: "Mekke" },
  { number: 53, name: "النجم", transliteration: "En-Nexhm", translation: "Ylli", ayahCount: 62, revelationType: "Mekke" },
  { number: 54, name: "القمر", transliteration: "El-Kamer", translation: "Hëna", ayahCount: 55, revelationType: "Mekke" },
  { number: 55, name: "الرحمن", transliteration: "Er-Rahman", translation: "I Gjithëmëshirshmi", ayahCount: 78, revelationType: "Medine" },
  { number: 56, name: "الواقعة", transliteration: "El-Vaki'a", translation: "Ngjarja", ayahCount: 96, revelationType: "Mekke" },
  { number: 57, name: "الحديد", transliteration: "El-Hadid", translation: "Hekuri", ayahCount: 29, revelationType: "Medine" },
  { number: 58, name: "المجادلة", transliteration: "El-Muxhadele", translation: "Debatuesja", ayahCount: 22, revelationType: "Medine" },
  { number: 59, name: "الحشر", transliteration: "El-Hashr", translation: "Grumbullimi", ayahCount: 24, revelationType: "Medine" },
  { number: 60, name: "الممتحنة", transliteration: "El-Mumtehine", translation: "E Provuara", ayahCount: 13, revelationType: "Medine" },
  { number: 61, name: "الصف", transliteration: "Es-Saff", translation: "Rreshti", ayahCount: 14, revelationType: "Medine" },
  { number: 62, name: "الجمعة", transliteration: "El-Xhumu'a", translation: "E Premtja", ayahCount: 11, revelationType: "Medine" },
  { number: 63, name: "المنافقون", transliteration: "El-Munafikun", translation: "Hipokritët", ayahCount: 11, revelationType: "Medine" },
  { number: 64, name: "التغابن", transliteration: "Et-Tegabun", translation: "Humbja", ayahCount: 18, revelationType: "Medine" },
  { number: 65, name: "الطلاق", transliteration: "Et-Talak", translation: "Divorci", ayahCount: 12, revelationType: "Medine" },
  { number: 66, name: "التحريم", transliteration: "Et-Tahrim", translation: "Ndalimi", ayahCount: 12, revelationType: "Medine" },
  { number: 67, name: "الملك", transliteration: "El-Mulk", translation: "Sundimi", ayahCount: 30, revelationType: "Mekke" },
  { number: 68, name: "القلم", transliteration: "El-Kalem", translation: "Lapsi", ayahCount: 52, revelationType: "Mekke" },
  { number: 69, name: "الحاقة", transliteration: "El-Hakka", translation: "E Vërteta", ayahCount: 52, revelationType: "Mekke" },
  { number: 70, name: "المعارج", transliteration: "El-Me'arixh", translation: "Shkallët", ayahCount: 44, revelationType: "Mekke" },
  { number: 71, name: "نوح", transliteration: "Nuh", translation: "Nuhu", ayahCount: 28, revelationType: "Mekke" },
  { number: 72, name: "الجن", transliteration: "El-Xhinn", translation: "Xhinët", ayahCount: 28, revelationType: "Mekke" },
  { number: 73, name: "المزمل", transliteration: "El-Muzzemmil", translation: "I Mbështjelluri", ayahCount: 20, revelationType: "Mekke" },
  { number: 74, name: "المدثر", transliteration: "El-Muddethir", translation: "I Mbuluri", ayahCount: 56, revelationType: "Mekke" },
  { number: 75, name: "القيامة", transliteration: "El-Kijame", translation: "Ringjallja", ayahCount: 40, revelationType: "Mekke" },
  { number: 76, name: "الإنسان", transliteration: "El-Insan", translation: "Njeriu", ayahCount: 31, revelationType: "Medine" },
  { number: 77, name: "المرسلات", transliteration: "El-Murselat", translation: "Të Dërguarat", ayahCount: 50, revelationType: "Mekke" },
  { number: 78, name: "النبأ", transliteration: "En-Nebe", translation: "Lajmi", ayahCount: 40, revelationType: "Mekke" },
  { number: 79, name: "النازعات", transliteration: "En-Nazi'at", translation: "Shkulësit", ayahCount: 46, revelationType: "Mekke" },
  { number: 80, name: "عبس", transliteration: "Abese", translation: "Ai Vrenjti", ayahCount: 42, revelationType: "Mekke" },
  { number: 81, name: "التكوير", transliteration: "Et-Tekvir", translation: "Mbështjellja", ayahCount: 29, revelationType: "Mekke" },
  { number: 82, name: "الانفطار", transliteration: "El-Infitar", translation: "Çarja", ayahCount: 19, revelationType: "Mekke" },
  { number: 83, name: "المطففين", transliteration: "El-Mutaffifin", translation: "Mashtruesit", ayahCount: 36, revelationType: "Mekke" },
  { number: 84, name: "الانشقاق", transliteration: "El-Inshikak", translation: "Shqyerja", ayahCount: 25, revelationType: "Mekke" },
  { number: 85, name: "البروج", transliteration: "El-Buruxh", translation: "Yjësitë", ayahCount: 22, revelationType: "Mekke" },
  { number: 86, name: "الطارق", transliteration: "Et-Tarik", translation: "Ylli i Natës", ayahCount: 17, revelationType: "Mekke" },
  { number: 87, name: "الأعلى", transliteration: "El-A'la", translation: "Më i Larti", ayahCount: 19, revelationType: "Mekke" },
  { number: 88, name: "الغاشية", transliteration: "El-Gashije", translation: "Mbuluesja", ayahCount: 26, revelationType: "Mekke" },
  { number: 89, name: "الفجر", transliteration: "El-Fexhr", translation: "Agimi", ayahCount: 30, revelationType: "Mekke" },
  { number: 90, name: "البلد", transliteration: "El-Beled", translation: "Qyteti", ayahCount: 20, revelationType: "Mekke" },
  { number: 91, name: "الشمس", transliteration: "Esh-Shems", translation: "Dielli", ayahCount: 15, revelationType: "Mekke" },
  { number: 92, name: "الليل", transliteration: "El-Lejl", translation: "Nata", ayahCount: 21, revelationType: "Mekke" },
  { number: 93, name: "الضحى", transliteration: "Ed-Duha", translation: "Paraditja", ayahCount: 11, revelationType: "Mekke" },
  { number: 94, name: "الشرح", transliteration: "Esh-Sherh", translation: "Zgjerimi", ayahCount: 8, revelationType: "Mekke" },
  { number: 95, name: "التين", transliteration: "Et-Tin", translation: "Fiku", ayahCount: 8, revelationType: "Mekke" },
  { number: 96, name: "العلق", transliteration: "El-Alek", translation: "Mpiksja", ayahCount: 19, revelationType: "Mekke" },
  { number: 97, name: "القدر", transliteration: "El-Kadr", translation: "Kadri", ayahCount: 5, revelationType: "Mekke" },
  { number: 98, name: "البينة", transliteration: "El-Bejjine", translation: "Prova", ayahCount: 8, revelationType: "Medine" },
  { number: 99, name: "الزلزلة", transliteration: "Ez-Zelzele", translation: "Tërmeti", ayahCount: 8, revelationType: "Medine" },
  { number: 100, name: "العاديات", transliteration: "El-Adijat", translation: "Galopuesit", ayahCount: 11, revelationType: "Mekke" },
  { number: 101, name: "القارعة", transliteration: "El-Kari'a", translation: "Trokitësja", ayahCount: 11, revelationType: "Mekke" },
  { number: 102, name: "التكاثر", transliteration: "Et-Tekathur", translation: "Grumbullimi", ayahCount: 8, revelationType: "Mekke" },
  { number: 103, name: "العصر", transliteration: "El-Asr", translation: "Koha", ayahCount: 3, revelationType: "Mekke" },
  { number: 104, name: "الهمزة", transliteration: "El-Humeze", translation: "Përgojiësi", ayahCount: 9, revelationType: "Mekke" },
  { number: 105, name: "الفيل", transliteration: "El-Fil", translation: "Elefanti", ayahCount: 5, revelationType: "Mekke" },
  { number: 106, name: "قريش", transliteration: "Kurejsh", translation: "Kurejshitët", ayahCount: 4, revelationType: "Mekke" },
  { number: 107, name: "الماعون", transliteration: "El-Ma'un", translation: "Ndihma e Vogël", ayahCount: 7, revelationType: "Mekke" },
  { number: 108, name: "الكوثر", transliteration: "El-Keuther", translation: "Bollëku", ayahCount: 3, revelationType: "Mekke" },
  { number: 109, name: "الكافرون", transliteration: "El-Kafirun", translation: "Mohuesit", ayahCount: 6, revelationType: "Mekke" },
  { number: 110, name: "النصر", transliteration: "En-Nasr", translation: "Ndihma", ayahCount: 3, revelationType: "Medine" },
  { number: 111, name: "المسد", transliteration: "El-Mesed", translation: "Litari", ayahCount: 5, revelationType: "Mekke" },
  { number: 112, name: "الإخلاص", transliteration: "El-Ihlas", translation: "Sinqeriteti", ayahCount: 4, revelationType: "Mekke" },
  { number: 113, name: "الفلق", transliteration: "El-Felek", translation: "Agimi", ayahCount: 5, revelationType: "Mekke" },
  { number: 114, name: "الناس", transliteration: "En-Nas", translation: "Njerëzit", ayahCount: 6, revelationType: "Mekke" },
];
